# Generated by Django 5.1 on 2024-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Maculino'), (2, 'Femenino'), (3, 'Gay'), (4, 'Helicptero Apache'), (5, 'Motor de Lancha'), (6, 'No especificado')], default=6, verbose_name='genero')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('correoInstitucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('grado', models.PositiveIntegerField(blank=True, choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto')], null=True, verbose_name='grado')),
                ('seccion', models.PositiveIntegerField(verbose_name='Seccion')),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aula', to='Edificio.aula')),
            ],
            options={
                'db_table': 'Maestros',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Maculino'), (2, 'Femenino'), (3, 'Gay'), (4, 'Helicptero Apache'), (5, 'Motor de Lancha'), (6, 'No especificado')], default=6, verbose_name='genero')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('correoInstitucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombre_tutor', models.CharField(max_length=100, verbose_name='nombre del tutor')),
                ('apellido_tutor', models.CharField(max_length=100, verbose_name='apellido del tutor')),
                ('telefono_tutor', models.CharField(max_length=10, verbose_name='telefono del tutor')),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='Usuario.maestro')),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
    ]
