# Generated by Django 5.1 on 2024-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='telefono',
            field=models.CharField(default=1, max_length=10, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maculino'), (2, 'Femenino'), (3, 'No especificado')], default=3, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maculino'), (2, 'Femenino'), (3, 'No especificado')], default=3, verbose_name='genero'),
        ),
    ]
