# Generated by Django 5.1 on 2024-08-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la clase')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo de la clase')),
            ],
            options={
                'db_table': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(default=2024, editable=False)),
                ('n_bimestre', models.CharField(choices=[('I', 'Primer semestre'), ('II', 'Segundo bimestre')], max_length=2, verbose_name='bimestre')),
            ],
            options={
                'db_table': 'Bimestres',
                'constraints': [models.UniqueConstraint(fields=('anio', 'n_bimestre'), name='No pueden haber dos semestres iguales en un mismo año')],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Academico.asignatura')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Usuario.maestro')),
            ],
            options={
                'db_table': 'Planes',
                'constraints': [models.UniqueConstraint(fields=('maestro', 'clase'), name='Un maestro no puede llevar clases repetidas')],
            },
        ),
    ]
