# Generated by Django 5.1 on 2024-08-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='bimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_estudio', to='Academico.bimestre'),
            preserve_default=False,
        ),
    ]
