# Generated by Django 5.1 on 2024-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_planestudio_bimestre'),
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planestudio',
            name='Un maestro no puede llevar clases repetidas',
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('maestro', 'clase', 'bimestre'), name='Un maestro no puede llevar clases repetidas en el mismo bimestre'),
        ),
    ]
