# Generated by Django 5.1 on 2024-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('direccion', models.TextField(verbose_name='direccion')),
                ('telefono', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'escuela',
                'verbose_name_plural': 'escuelas',
                'db_table': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=15, verbose_name='Codigo Aula')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='Edificio.escuela')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'db_table': 'Aula',
            },
        ),
    ]
