# Generated by Django 5.1 on 2024-08-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='Codigo',
            new_name='codigo',
        ),
    ]
