# Generated by Django 5.1 on 2024-08-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0002_rename_codigo_aula_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='codigo',
            field=models.CharField(max_length=15, unique=True, verbose_name='Codigo Aula'),
        ),
    ]
