# Generated by Django 5.1 on 2024-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la clase')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo de la clase')),
            ],
            options={
                'db_table': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(default=2024, editable=False)),
                ('n_bimestre', models.CharField(choices=[('I', 'Primer semestre'), ('II', 'Segundo bimestre')], max_length=2, verbose_name='bimestre')),
            ],
        ),
    ]
