# Generated by Django 5.1 on 2024-08-22 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('valor', models.PositiveSmallIntegerField(default=0, verbose_name='valor de la tarea')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivosEvaluacion/', verbose_name='archivo adjunto')),
                ('parcial', models.PositiveIntegerField(choices=[(1, 'Primer parcial'), (2, 'Segundo parcial'), (3, 'Tercer parcial'), (4, 'Cuarto parcial')], default=1, verbose_name='Parcial')),
            ],
            options={
                'db_table': 'Evaluaciones',
            },
        ),
    ]
