# Generated by Django 5.1 on 2024-08-22 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0001_initial'),
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Calificacion.asignatura')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Usuario.maestro')),
            ],
        ),
    ]
