# Generated by Django 5.1 on 2024-08-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
        ('Calificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='plan_estudio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='Academico.planestudio', verbose_name='Plan de Estudio'),
            preserve_default=False,
        ),
    ]
