# Generated by Django 5.1 on 2024-08-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0002_evaluacion_plan_estudio'),
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(default=0, verbose_name='Calificación')),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Tarea pendiente'), (2, 'Tarea en revició'), (3, 'Tarea entregada'), (4, 'Tarea no entregada')], default=1, verbose_name='Estado actual')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='archivosCalificacion/', verbose_name='Evidencia de la tarea')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Calificaciones', to='Usuario.alumno', verbose_name='Alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='Calificacion.evaluacion', verbose_name='Evaluacion')),
            ],
            options={
                'db_table': 'Calificaciones',
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'alumno'), name='Un alumno no puede tene 2 califícaciones de la misma tarea')],
            },
        ),
    ]
