# Generated by Django 5.1 on 2024-08-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0002_planestudio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bimestre',
            table='Bimestres',
        ),
        migrations.AlterModelTable(
            name='planestudio',
            table='PlanesDeEstudio',
        ),
    ]
