# Generated by Django 5.1 on 2024-08-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0003_calificacion'),
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='Usuario.alumno', verbose_name='alumno'),
        ),
    ]
