# Generated by Django 5.1 on 2024-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0003_alter_bimestre_table_alter_planestudio_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bimestre',
            constraint=models.UniqueConstraint(fields=('anio', 'n_bimestre'), name='No pueden haber dos semestres iguales en un mismo año'),
        ),
    ]
