# Generated by Django 5.1 on 2024-08-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacion', '0004_bimestre_no_pueden_haber_dos_semestres_iguales_en_un_mismo_año'),
        ('Usuario', '0002_alter_maestro_grado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('maestro', 'clase'), name='Un maestro no puede llevar clases repetidas'),
        ),
        migrations.AlterModelTable(
            name='planestudio',
            table='Planes',
        ),
    ]
